#!/bin/bash
set -e

echo "PostgreSQL starting..."
psql -U "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE $DOCKER_DB_USER WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$DOCKER_DB_PASSWORD';
    CREATE DATABASE $DOCKER_DB_NAME OWNER $DOCKER_DB_USER;
EOSQL
